---
- name: ops445 Configurations
  hosts: svethanayagam3
  user: student
  become: yes
  tasks:
    - name: Update Apache
      yum:
        name: httpd
        state: latest

    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set hostname to svethanayagam3
      hostname:
        name: svethanayagam3

    - name: Create a new user svethanayagam3
      user:
        name: svethanayagam3
        groups: wheel
        state: present

    - name: Allow passwordless sudo for the user
      copy:
        dest: "/etc/sudoers.d/svethanayagam3"
        content: |
          svethanayagam3 ALL=(ALL) NOPASSWD:ALL
        owner: root
        group: root
        mode: '0440'

    - name: Configure passwordless SSH for the new user
      authorized_key:
        user: svethanayagam3
        state: present
        key: "{{ lookup('file', '/home/svethanayagam3/.ssh/id_rsa.pub') }}"

    - name: Create directory structure for labs
      file:
        path: "/home/svethanayagam3/ops445/lab{{ item }}"
        state: directory
        owner: svethanayagam3  
        group: svethanayagam3  
        mode: '0755'
      with_items:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
